config/routes.rb
Giveservice::Application.routes.draw do
  devise_for :users
  resources :opportunities, :organizations

  resources :pages, :controller => 'high_voltage/pages', :only => [:index]

  root :to => 'pages#show', :id => 'index'

end

app/models/opportunities_user.rb
class OpportunitiesUser < ActiveRecord::Base
  # Associations
  belongs_to :opportunity
  belongs_to :user
  # attr_accessible :title, :body
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base

  # Associations
  belongs_to :organization
  has_many :opportunities_users
  has_many :users, through: :opportunities_users

  # Accessible Attributes
  attr_accessible :duration, :title
end

app/models/organization.rb
class Organization < ActiveRecord::Base

  # Associations
  # has_many :opportunities
  has_many :organizations_users
  has_many :users, through: :organizations_users

  # Accessible Attributes
  attr_accessible :description, :title
end

app/models/organizations_user.rb
class OrganizationsUser < ActiveRecord::Base

  # Associations
  belongs_to :organization
  belongs_to :user
  
  # Accessible Attributes
  attr_accessible :organization_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base

  # Associations
  has_many :organizations_users
  has_many :organizations, through: :organizations_users
  has_many :opportunities_users
  has_many :opportunities, through: :opportunities_users
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  set_tab :opportunities

  def index
    @opportunities = Opportunity.all
  end

  def show

  end

  def new
    @opportunity = Opportunity.new

  end

  def create
    @opportunity = Opportunity.new(params[:opportunity])
    if @opportunity.save
      redirect_to opportunities_path
    else
      render :new
    end

  end

  def edit

  end

  def update

  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  set_tab :organizations
  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end 

  def create
  end

  def edit
  end

  def update
  end

end

app/controllers/pages_controller.rb
class PagesController < HighVoltage::PagesController
  set_tab :pages
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="row">
    <div class="span12">
      <p class="pull-left">&copy; <%= Date.today.year %> - Giveservice.org, All rights reserved.</p>
      <p class="pull-right"><a href="#">Terms of Use</a> &nbsp;|&nbsp; <a href="#">Privacy Policy</a></p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
    <div class="container">
      <div class="row branding">
        <div class="span6">
          <h1 class="pull-left"><%= link_to "giveservice.org", root_path %></h1>
        </div>                  
        <div class="span6">
          <p class="pull-right userInfo"><i class="icon-user"></i> Welcome <strong>Guest!</strong> &nbsp;<%= current_user ? link_to("logout", destroy_user_session_path, method: :delete) : link_to("Please Login", new_user_session_path) %></p>
        </div>                  
      </div>
      <div class="row navigation">
        <div class="span12">
        <%= tabs_tag :builder => MenuTabBuilder, open_tabs: {class: 'nav nav-tabs'} do |tab| %>
          <%= tab.pages          'Home', root_path %>
          <%= tab.opportunities 'Opportunities', opportunities_path %>
          <%= tab.organizations 'Organizations', organizations_path %>
          <%= tab.blog          'Blog', root_path %>
        <% end %>
        </div>
      </div>
    </div>        
  </div>

app/views/layouts/_quick-sign-up.html.erb
<form action="/users" method="post" class="well quickSignupForm">
  <h3>Quick Sign-up</h3>
  <label>Email</label>
  <input type="text" name="user[email]" class="span3" placeholder="">
  <label>Password</label>
  <input type="password" name="user[password]" class="span3" placeholder="">
  <label>Password Confirmation</label>
  <input type="password" name="user[password_confirmation]" class="span3" placeholder="">
  <button class="btn btn-large btn-success btnSignup">&nbsp;&nbsp; Sign up &nbsp;&nbsp;</button>
</form>

app/views/layouts/_side_bar.html.erb
<div class="span4 sidebar">
<% if current_user -%>
  <h2><%= link_to "Edit Profile", edit_user_registration_path, html_options = { class: "btn btn-large btn-success" } %></h2>
<% else%>
  <h2><%= link_to "Get an account now", new_user_registration_path, html_options = { class: "btn btn-large btn-warning" } %></h2>
<% end %>
  <%= render "layouts/quick-sign-up" %>
  <h3>Where do i go from here?</h3>
  <p>
    Nullam quis risus eget urna <a href="#">mollis ornare</a> vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes.
  </p>
  <h4>
    <a href="#">Get an account now</a>
  </h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Giveservice</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper">
  <%= render 'layouts/header' %>
  <%= yield %>
</div>
</body>
</html>

app/views/opportunities/_side_bar.html.erb
<div class="span4 sidebar">
<% if current_user -%>
  <h2><%= link_to "Create Opportunity", new_opportunity_path, html_options = { class: "btn btn-large btn-success" } %></h2>
<% else%>
  <h2><%= link_to "Get an account now", new_user_registration_path, html_options = { class: "btn btn-large btn-warning" } %></h2>
<% end %>
  <%= render "layouts/quick-sign-up" %>
  <h3>Where do i go from here?</h3>
  <p>
    Nullam quis risus eget urna <a href="#">mollis ornare</a> vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes.
  </p>
  <h4>
    <a href="#">Get an account now</a>
  </h4>
</div>

app/views/opportunities/index.html.erb
<div class="container content">
  <div class="row">
    <div class="span8 leftContent">
      <h2>Opportunities</h2>
      <table class="table table-bordered table-striped table-spacer">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Duration</th>
            <th>&nbsp;</th>
          </tr>
        </thead>
        <tbody>
          <% @opportunities.each do |opportunity| %>
            <tr>
              <td><%= opportunity.id %></td>
              <td><%= opportunity.title %></td>
              <td><%= opportunity.duration %></td>
              <td>
                <% if current_user -%>
                  <%= link_to 'Join', root_path %>
                <% else %> 
                  <%= link_to 'Sign Up', new_user_registration_path %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= render "opportunities/side_bar" %> 
  </div>
</div>

app/views/opportunities/new.html.erb
<div class="container content">
  <div class="row">
    <div class="well offset3 span6">
      <h2>Create Opportunity</h2>
        <%= simple_form_for(@opportunity, :html => { :class => 'form-horizontal' }) do |f| %>
        <div class="form-inputs">
          <%= f.input :title %>
        </div>
  
        <div class="form-actions">
          <%= f.button :submit, "Update" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/organizations/_side_bar.html.erb
<div class="span4 sidebar">
<% if current_user -%>
  <h2><%= link_to "Create an Organization", new_organization_path, html_options = { class: "btn btn-large btn-success" } %></h2>
<% else%>
<% end %>
  <form class="well quickSignupForm">
    <h3>Quick Sign-up</h3>
    <label>Email</label>
    <input type="text" class="span3" placeholder="">
    <label>Password</label>
    <input type="password" class="span3" placeholder="">
    <label>Password Confirmation</label>
    <input type="password" class="span3" placeholder="">
    <button class="btn btn-large btn-success btnSignup">&nbsp;&nbsp; Sign up &nbsp;&nbsp;</button>
  </form>
  <h3>Where do i go from here?</h3>
  <p>
    Nullam quis risus eget urna <a href="#">mollis ornare</a> vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes.
  </p>
  <h4>
    <a href="#">Get an account now</a>
  </h4>
</div>

app/views/organizations/index.html.erb
<div class="container content">
  <div class="row">
    <div class="span8 leftContent">
      <h2>Organizations</h2>
      <table class="table table-bordered table-striped table-spacer">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>&nbsp</th>
          </tr>
        </thead>
        <tbody>
          <% @organizations.each do |organization| %>
            <tr>
              <td><%= organization.id %></td>
              <td><%= organization.title %></td>
              <td>Links</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <%= render "organizations/side_bar" %> 
  </div>
</div>

app/views/organizations/new.html.erb
<div class="container content">
  <div class="row">
    <div class="span8">
      <h1>Create New Organization</h1>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container content">
  <div class="row">
    <div class="span8 leftContent">
      <h2>How to Give Service?</h2>
      <div class="row">
        <div class="span8">
          <p class="cntPara simpleDesign">
            <strong class="lead">Register</strong> Nullam quis risus eget urna <a href="#">mollis ornare</a> vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p> 
        </div>
        <div class="span8">
          <p class="cntPara simpleDesign">
            <strong class="lead">Add Skills</strong> Nullam quis risus eget urna <a href="#">mollis ornare</a> vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p> 
        </div>
        <div class="span8">
          <p class="cntPara easyUse">
            <strong class="lead">Search</strong> Nullam quis risus eget urna <a href="#">mollis ornare</a> vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p> 
        </div>                                        
      </div>
      <h2>Have a service opportunity?</h2>
      <div class="row">
        <div class="span8">
          <p class="cntPara simpleDesign">
            <strong class="lead">Register</strong> Nullam quis risus eget urna <a href="#">mollis ornare</a> vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p> 
        </div>
        <div class="span8">
          <p class="cntPara simpleDesign">
            <strong class="lead">Add Skills needed</strong> Nullam quis risus eget urna <a href="#">mollis ornare</a> vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          </p> 
        </div>
      </div>
      <hr/>
      <div class="row">
        <div class="span8">
          <h3 class="signupTeaser"><a href="#">Don't miss out, create account today!</a></h3>
        </div>                                        
      </div>
      <hr/>
      <div class="row">
        <div class="span8">
          <h3 class="quickTour"></h3>
          <ul class="thumbnails">
            <li class="span2">
              <a href="#" class="thumbnail">
                <img src="http://placehold.it/160x120" alt="">
              </a>
            </li>
            <li class="span2">
              <a href="#" class="thumbnail">
                <img src="http://placehold.it/160x120" alt="">
              </a>
            </li>
            <li class="span2">
              <a href="#" class="thumbnail">
                <img src="http://placehold.it/160x120" alt="">
              </a>
            </li>
            <li class="span2">
              <a href="#" class="thumbnail">
                <img src="http://placehold.it/160x120" alt="">
              </a>
            </li>
          </ul>
        </div>                                        
      </div>
    </div>
   <%= render "layouts/side_bar" %> 
  </div>
  <%= render "layouts/footer" %> 
</div>